steps:
  # Step 1: Install dependencies (Frontend & Backend)
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Frontend deps
        cd "new UI"
        npm install --legacy-peer-deps
    id: 'install-deps'

  # Step 2a: Frontend Verification (Lint)
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd "new UI"
        npm run lint
    id: 'frontend-verify'
    waitFor: ['install-deps']

  # Step 2b: Backend Verification (Test)
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install pytest -r requirements.txt
        export PYTHONPATH=$$PYTHONPATH:.
        pytest
    id: 'unit-tests'
    waitFor: ['install-deps']

  # Step 3: Create deployment package
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        tar -czf deployment-${SHORT_SHA}.tar.gz \
          --exclude=venv \
          --exclude=__pycache__ \
          --exclude=.git \
          --exclude=node_modules \
          --exclude='new UI/node_modules' \
          .
        
        gsutil cp deployment-${SHORT_SHA}.tar.gz gs://${_ARTIFACT_BUCKET}/
    id: 'create-package'
    waitFor: ['unit-tests']

  # Step 4: Deploy to Compute Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Download artifact and script
        gcloud compute ssh ${_INSTANCE_NAME} \
          --project=${_PROJECT_ID} \
          --zone=${_ZONE} \
          --command="gsutil cp gs://${_ARTIFACT_BUCKET}/deployment-${SHORT_SHA}.tar.gz /opt/hero_lib/deployment.tar.gz"

        gcloud compute scp scripts/deploy.sh scripts/rollback.sh ${_INSTANCE_NAME}:/tmp/ \
          --project=${_PROJECT_ID} \
          --zone=${_ZONE}
        
        # Execute
        gcloud compute ssh ${_INSTANCE_NAME} \
          --project=${_PROJECT_ID} \
          --zone=${_ZONE} \
          --command="chmod +x /tmp/deploy.sh /tmp/rollback.sh && sudo cp /tmp/rollback.sh /usr/local/bin/rollback-hero && sudo chmod +x /usr/local/bin/rollback-hero && /tmp/deploy.sh"
    id: 'deploy'
    waitFor: ['create-package']

  # Step 5: Health check
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting 30 seconds for application to fully start..."
        sleep 30
        INSTANCE_IP=$$(gcloud compute instances describe ${_INSTANCE_NAME} \
          --project=${_PROJECT_ID} \
          --zone=${_ZONE} \
          --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
        
        echo "Performing health check on http://$$INSTANCE_IP:${_APP_PORT}/health"
        
        for i in {1..12}; do
          if curl -f "http://$$INSTANCE_IP:${_APP_PORT}/health"; then
            echo "Health check passed!"
            exit 0
          fi
          echo "Attempt $$i failed, retrying in 5s..."
          sleep 5
        done
        
        echo "Health check failed after 12 attempts"
        exit 1
    id: 'health-check'
    waitFor: ['deploy']

# Substitution variables
substitutions:
  _INSTANCE_NAME: 'hero-lib-instance'
  _ZONE: 'us-central1-a'
  _PROJECT_ID: 'ci-cd-480509'
  _ARTIFACT_BUCKET: 'hero-lib-artifacts-ci-cd-480509'
  _APP_PORT: '5000' # Flask default is usually 5000, changed from 3000

timeout: '1800s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET}/builds/${BUILD_ID}'
    paths: ['deployment-${SHORT_SHA}.tar.gz']