# cloudbuild.yaml
# GCP Cloud Build configuration for Python CI/CD pipeline

steps:
  # Step 0: Checkout code (required because we use --no-source)
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Osaram-007/hero_lib-main.git', '.']
    id: 'checkout'

  # Step 1: Install dependencies
  - name: 'python:3.9'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']
    id: 'install-deps'
    waitFor: ['checkout']

  # Step 2: Run linting
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install pylint
        pylint --fail-under=5 hero_lib || echo "Linting failed but continuing..."
    id: 'lint'
    waitFor: ['install-deps']

  # Step 3: Run unit tests
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install pytest -r requirements.txt
        export PYTHONPATH=$$PYTHONPATH:.
        pytest
    id: 'unit-tests'
    waitFor: ['install-deps']

  # Step 4: Create deployment package
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p deployment-package
        cp -r hero_lib scripts requirements.txt setup.py deployment-package/
        tar -czf deployment-${SHORT_SHA}.tar.gz -C deployment-package .
        gsutil cp deployment-${SHORT_SHA}.tar.gz gs://${_ARTIFACT_BUCKET}/
    id: 'create-package'
    waitFor: ['unit-tests']

  # Step 5: Deploy to Compute Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh ${_INSTANCE_NAME} \
          --zone=${_ZONE} \
          --command="
            set -e
            echo 'Starting deployment...'
            
            # Install necessary packages 
            sudo apt-get update
            # Install Python env and Node/PM2 for process management if not present
            if ! command -v pip3 &> /dev/null; then
                sudo apt-get install -y python3-pip python3-venv
            fi
            if ! command -v npm &> /dev/null; then
                sudo apt-get install -y nodejs npm
            fi
            
            # Create deployment directory
            sudo mkdir -p /opt/hero_lib
            sudo chown -R ubuntu:ubuntu /opt/hero_lib
            cd /opt/hero_lib
            
            # Download deployment package
            gsutil cp gs://${_ARTIFACT_BUCKET}/deployment-${SHORT_SHA}.tar.gz .
            
            # Backup previous version
            if [ -d 'current' ]; then
              mv current previous_$(date +%Y%m%d_%H%M%S)
            fi
            
            # Extract new version
            mkdir -p current
            tar -xzf deployment-${SHORT_SHA}.tar.gz -C current/
            cd current
            
            # Setup Virtual Environment
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Install PM2 if not exists
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi
            
            # Stop existing application
            pm2 stop hero_lib || true
            
            # Start application with PM2 (using python interpreter)
            # Assuming app.py is the entry point and runs on port 3000 or defined port
            # We explicitly invoke python from the venv
            pm2 start hero_lib/app.py --name hero_lib --interpreter ./venv/bin/python3
            pm2 save
            
            echo 'Waiting 5 seconds for app to initialize...'
            sleep 5
            echo '--- Application Logs (Start) ---'
            pm2 logs hero_lib --lines 20 --nostream --err --out
            echo '--- Application Logs (End) ---'
            
            # Setup PM2 to start on reboot
            sudo env PATH=$$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
            
            # Clean up
            rm ../deployment-${SHORT_SHA}.tar.gz
            
            echo 'Deployment completed successfully!'
          "
    id: 'deploy'
    waitFor: ['create-package']

  # Step 6: Health check
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting 30 seconds for application to fully start..."
        sleep 30
        INSTANCE_IP=$$(gcloud compute instances describe ${_INSTANCE_NAME} \
          --zone=${_ZONE} \
          --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
        
        echo "Performing health check on http://$$INSTANCE_IP:${_APP_PORT}/health"
        
        for i in {1..12}; do
          if curl -f "http://$$INSTANCE_IP:${_APP_PORT}/health"; then
            echo "Health check passed!"
            exit 0
          fi
          echo "Attempt $$i failed, retrying in 5s..."
          sleep 5
        done
        
        echo "Health check failed after 12 attempts"
        exit 1
    id: 'health-check'
    waitFor: ['deploy']

# Substitution variables
substitutions:
  _INSTANCE_NAME: 'hero-lib-instance'
  _ZONE: 'us-central1-a'
  _ARTIFACT_BUCKET: 'hero-lib-artifacts-ci-cd-480509'
  _APP_PORT: '5000' # Flask default is usually 5000, changed from 3000

timeout: '1800s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET}/builds/${BUILD_ID}'
    paths: ['deployment-${SHORT_SHA}.tar.gz']