FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend source code
COPY hero_lib/ ./hero_lib/
COPY books_data/ ./books_data/

ENV PORT=5000
EXPOSE $PORT
ENV PYTHONUNBUFFERED=1

CMD sh -c "gunicorn --bind 0.0.0.0:${PORT:-5000} hero_lib.app:app"
